In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [2]:
from graphtorch import SparseMatrix, SparseModel
import numpy as np
import torch 
import torch.nn as nn

Example 2

![](img/example2_1.png)

![](img/example2_2.png)

In [3]:
mat2 = np.array([[2,0,0,0,0,0],
                [0,0,0,3,0,1]])
in_dim = 5
out_dim = 1
mat_wann2 = SparseMatrix(mat2, in_dim, out_dim)  

In [4]:
mat_wann2.connection_count

3

In [5]:
activations = [None, None, nn.ReLU(), nn.Sigmoid()]  
constant_weight = 1 
model = SparseModel(mat_wann2, activations, constant_weight)

numpy_input = np.array([[1,2,3,4,5],  
                        [6,7,8,9,10],  
                        [11,12,13,14,15]]) 

numpy_input = torch.from_numpy(numpy_input).float()  
output, nodes = model(numpy_input)  

In [6]:
model.connection_count

3

In [7]:
output

tensor([[ 1.9820],
        [ 6.9999],
        [12.0000]], grad_fn=<AddBackward0>)

In [8]:
nodes

{'hidden_0': tensor([[ 1.],
         [ 6.],
         [11.]], grad_fn=<ReluBackward0>), 'output_0': tensor([[ 1.9820],
         [ 6.9999],
         [12.0000]], grad_fn=<AddBackward0>)}

In [9]:
# the network should double the input of when weights are all 1
numpy_output = np.array([[2],
                        [14],
                        [24]])
numpy_output = torch.from_numpy(numpy_output).float()
numpy_output

tensor([[ 2.],
        [14.],
        [24.]])

In [10]:
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters())
for epoch in range(10) : 
    model.train()
    optimizer.zero_grad()
    output, nodes = model(numpy_input)  
    loss = criterion(output, numpy_output)
    loss.backward()
    optimizer.step()
    
    print([x for x in model.parameters()])
    print('loss : %.3f' % loss.item())

[Parameter containing:
tensor([[1.0010]], requires_grad=True), Parameter containing:
tensor([[1.0010]], requires_grad=True), Parameter containing:
tensor([[1.0010]], requires_grad=True), Parameter containing:
tensor([[1.]], requires_grad=True)]
loss : 64.334
[Parameter containing:
tensor([[1.0020]], requires_grad=True), Parameter containing:
tensor([[1.0020]], requires_grad=True), Parameter containing:
tensor([[1.0020]], requires_grad=True), Parameter containing:
tensor([[1.]], requires_grad=True)]
loss : 64.102
[Parameter containing:
tensor([[1.0030]], requires_grad=True), Parameter containing:
tensor([[1.0030]], requires_grad=True), Parameter containing:
tensor([[1.0030]], requires_grad=True), Parameter containing:
tensor([[1.]], requires_grad=True)]
loss : 63.870
[Parameter containing:
tensor([[1.0040]], requires_grad=True), Parameter containing:
tensor([[1.0040]], requires_grad=True), Parameter containing:
tensor([[1.0040]], requires_grad=True), Parameter containing:
tensor([[1.]],

In [11]:
output

tensor([[ 2.0007],
        [ 7.1083],
        [12.1988]], grad_fn=<AddBackward0>)

In [12]:
numpy_output

tensor([[ 2.],
        [14.],
        [24.]])